# file: roles/init/tasks/main.yml
---

- name: Set up firewall
  shell: systemctl enable firewalld
  shell: systemctl start firewalld

- name: Install nano, git, emacs
  yum: pkg={{ item }} state=installed
  with_items:
     - git
     - nano
     - curl
     - emacs
